# Generated by Django 6.0.2 on 2026-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
