# Generated by Django 6.0.3 on 2026-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
